### ISSUE TITLE
GitHub download code needs to be nicer to github.com's servers

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-bugimporters#110]
At the time of writing, oh-bugimporters has difficulty downloading
all the bugs it wants to from github.com.

@ehashman discovered that GitHub throttles API requests after
5000 per hour.

**Comment by paulproteus** [comment]
#109 is a pull request to address this

See https://github.com/openhatch/oh-mainline/issues/1515 for user reports + serious debugging work.

**Comment by ehashman** [comment]
#109 should resolve this. We'll see after tonight's scrape!

**Comment by thomasballinger** [comment]
This doesn't seem addressed (unless this is a different issue). About half of the GitHub requests are failing, in a pattern that suggests rate limiting of some kindt [the relevant bits of the logs](https://gist.github.com/thomasballinger/4d063186febfe4190283)

**Comment by thomasballinger** [comment]
I'm having trouble running this code locally, so can't suggest code with confidence. 

The simplest fix looks to me like not using the [Scrapy basic auth middleware](http://doc.scrapy.org/en/latest/topics/downloader-middleware.html#module-scrapy.contrib.downloadermiddleware.httpauth) (though that feels like the "right" solution) but instead adding either adding `&client_id=xxxx&client_secret=yyyy' to the end of the urls before constructing `scrapy`[client key and secret](https://developer.github.com/v3/#oauth2-keysecret) at https://github.com/openhatch/oh-bugimporters/blob/master/bugimporters/github.py#L31 OR using contructing a header at this same spot (`scrapy.http.Request` takes a headers argument) with a manually constructed authentication header, as [described here](http://stackoverflow.com/questions/2407126/python-urllib2-basic-auth-problem) or using something in the stdlib to build the header, though everything I've found there seems roundabout.

The oauth client id and secret in the query parameters approach requires creating an oauth application ([several clicks on GitHub](https://github.com/settings/applications/new)). The simple auth solution requires creating a GitHub user whose username and password can be used in the script.

**Comment by paulproteus** [comment]
I think I can make this work with GitHub basic auth plus a personal access token. I'm looking into that now.

Thanks again to @thomasballinger for doing the research on this.

**Comment by paulproteus** [comment]
FWIW, I am running a fresh crawl right now, and we'll see if my changes to oh-bugimporters fix this. If so, I'll submit a pull request.

**Comment by ehashman** [comment]
@paulproteus can this be closed?

**Comment by paulproteus** [comment]
+1​
